server:
  port: 8080

spring:
  transaction:
    rollback-on-commit-failure: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rule_engine?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  resources:
    static-locations: /static/
# 配置mybatis
mybatis:
  mapper-locations: classpath*:/dao/**Dao.xml
  typeAliasesPackage: com.example.xyd.entity

# 配置pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql